### ISSUE TITLE
可能产生完全相同的两幅图

### ISSUE THREAD

**Issue by RinStel** [tigerlee/cube-wall#3]
我在练习中，有时会遇到完全相同的两幅图。为此我阅读了您的代码，发现了问题的来源
在 HTML 文件的第 194 行：
`let color = this.randomColor(m[x][x])`
根据形参的名字，我推测此处函数的实参应为 `this.matrix` 的 `this.point` 位置的颜色，**所以此行应改为**：
`let color = this.randomColor(m[x][y])`
望及修正此Bug，谢谢

**Comment by tigerlee** [comment]
已经修正，谢谢提醒。
